version: '2'
services:
    legaltechapp-app:
        image: legaltechapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://legaltechapp-mysql:3306/legaltechapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    legaltechapp-mysql:
        extends:
            file: mysql.yml
            service: legaltechapp-mysql
